// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMiLOP6NkISMiSod61EYZlQVCD6LCeCQ',
    appId: '1:608840655991:web:c9bc54fc378ee13c6dd272',
    messagingSenderId: '608840655991',
    // projectId: 'bus-university-baddf',
    // authDomain: 'bus-university-baddf.firebaseapp.com',
    // storageBucket: 'bus-university-baddf.appspot.com',
    projectId: 'bus-university-baddf',
    authDomain: 'bus-university-baddf.firebaseapp.com',
    storageBucket: 'bus-university-baddf.appspot.com',
    measurementId: 'G-1SJZY0E4GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjsXjKb9DBnVWA3NmZpoROzrrTLetGPBQ',
    appId: '1:608840655991:android:a37c7bd2d88f22756dd272',
    messagingSenderId: '608840655991',
    projectId: 'bus-university-baddf',
    storageBucket: 'bus-university-baddf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYFYeKApguLY2P4vaVQOqVz2U9ey4eJk',
    appId: '1:608840655991:ios:545149483b3c68e96dd272',
    messagingSenderId: '608840655991',
    projectId: 'bus-university-baddf',
    storageBucket: 'bus-university-baddf.appspot.com',
    iosBundleId: 'com.example.busUni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYFYeKApguLY2P4vaVQOqVz2U9ey4eJk',
    appId: '1:608840655991:ios:8ffb34c927c77c0a6dd272',
    messagingSenderId: '608840655991',
    projectId: 'bus-university-baddf',
    storageBucket: 'bus-university-baddf.appspot.com',
    iosBundleId: 'com.example.busUni.RunnerTests',
  );
}
